name: Download Files
permissions: write-all


on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run cmd
      run: |
        sudo wget https://github.com/anonvector/SlipNet/releases/download/v2.5.2/SlipNet-v2.5.2-full-release-arm64-v8a.apk

    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "majidzahedi"
        author_email: "majidzahedi@github.com"
        message: "Upload Files"
        add: "."
        push: "majidzahedi.GIT"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
