name: Download Files
permissions: write-all


on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run cmd
      run: |
        sudo wget https://github.com/AliRezaBeigy/paqetNG/releases/download/v1.0.4/app-arm64-v8a-release.apk

    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "majidzahedi"
        author_email: "majidzahedi@github.com"
        message: "Upload Files"
        add: "."
        push: "https://github.com/majidzahedi/dinasor.git"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
